version: '3'

services:

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'