# Generated by Django 3.1.7 on 2021-02-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('age', models.IntegerField(blank=True, default=None, null=True, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('status', models.IntegerField(choices=[(0, 'Не определено'), (1, 'Продает'), (2, 'Покупает'), (3, 'Продает/покупает')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Агенство',
                'verbose_name_plural': 'Агенства',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Не определено'), (1, 'Продажа'), (2, 'Аренда')], default=0, verbose_name='Статус')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realties', to='realty.client', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to='realty.company', verbose_name='Агенство')),
            ],
            options={
                'verbose_name': 'Риелтор',
                'verbose_name_plural': 'Риелторы',
            },
        ),
    ]
