# Generated by Django 3.1.7 on 2021-03-01 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import realty.custom_decimal_field


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('realty', '0002_auto_20210222_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', realty.custom_decimal_field.CustomDecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('amount_commission', realty.custom_decimal_field.CustomDecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма комиссии')),
                ('date_of_deal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата сделки')),
                ('agreement', models.FileField(upload_to='agreements', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='TypeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
            },
        ),
        migrations.CreateModel(
            name='TypeRealty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.RenameModel(
            old_name='Contract',
            new_name='TypeLayout',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='company',
        ),
        migrations.AlterModelOptions(
            name='typelayout',
            options={'verbose_name': 'Планировка', 'verbose_name_plural': 'Планировки'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='realty',
            name='contract',
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='realty',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='realty',
            name='count_rooms',
            field=models.IntegerField(default=0, verbose_name='Кол-во комнат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realty',
            name='floor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='realty',
            name='floors',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Этажность'),
        ),
        migrations.AddField(
            model_name='realty',
            name='square',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Площадь (общая/жилая/кухня)'),
        ),
        migrations.AddField(
            model_name='realty',
            name='type_deal',
            field=models.IntegerField(blank=True, choices=[(0, 'Не определено'), (1, 'Продажа'), (2, 'Аренда')], default=0, verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='realty',
            name='type_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realties', to='realty.typelayout', verbose_name='Тип планировки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price',
            field=realty.custom_decimal_field.CustomDecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='realty.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='deal',
            name='type_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.typepayment', verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='deal',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='company.worker', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='realty',
            name='type_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realties', to='realty.typematerial', verbose_name='Тип материала'),
        ),
        migrations.AddField(
            model_name='realty',
            name='type_realty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realties', to='realty.typerealty', verbose_name='Тип недвижимости'),
        ),
    ]
