# Generated by Django 3.1.7 on 2021-03-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210302_1352'),
        ('realty', '0003_auto_20210301_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='company.worker', verbose_name='Работник'),
        ),
    ]
