# Generated by Django 3.1.7 on 2021-03-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='kids',
        ),
        migrations.AddField(
            model_name='child',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='company.worker', verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
    ]
