# Generated by Django 3.1.7 on 2021-03-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_client_worker'),
        ('company', '0003_auto_20210302_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='realty.deal', verbose_name='Сделка'),
        ),
    ]
