# Generated by Django 3.1.7 on 2021-02-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Не активен'), (1, 'Активен')], default=1)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
