# Generated by Django 3.1.7 on 2021-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Неактивен'), (1, 'Активен')], default=1),
        ),
    ]
